####################
## Application
####################
spring.application.name=chatbot


####################
## MVC
####################
## tratar rotas inexistentes + impedir acesso a conteudo estatico
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false


####################
## Profiles
####################
spring.profiles.active=dev
