####################
## Server
####################
server.port=8080


####################
## Database
####################
spring.datasource.url=${DB_URL:jdbc:mysql://localhost/chatbot}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


####################
## JWT
####################
api.security.token.secret=${JWT_TOKEN:4206769}


####################
## Swagger
####################
## Configuracoes do Swagger/OpenAPI
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false


####################
## Logs
####################
## desabilitar(false)/habilitar(true) print de cada requisicao como operacao sql + print formatado
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

## desabilitar(never)/habilitar(always) log de erros em requisicoes
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never

## habilitar log de autenticacaoes
logging.level.org.springframework.security=WARN

## Log de erro do Swagger
logging.level.org.springdoc=OFF
logging.level.org.springframework.web=WARN
