####################
## Server
####################
server.port=8080


####################
## Database
####################
spring.datasource.url=${DB_URL:jdbc:mysql://localhost/chatbot}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


####################
## JWT
####################
api.security.token.secret=${JWT_TOKEN:4206769}


####################
## Swagger
####################
## Configuracoes do Swagger/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger.html
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.filter=true


####################
## Logs
####################
## desabilitar(false)/habilitar(true) print de cada requisicao como operacao sql + print formatado
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## desabilitar(never)/habilitar(always) log de erros em requisicoes
server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-binding-errors=always

## habilitar log de autenticacaoes
logging.level.org.springframework.security=DEBUG

## Log de erro do Swagger
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG
