####################
## Application
####################
spring.application.name=chatbot


####################
## MVC
####################
## tratar rotas inexistentes + impedir acesso a conteudo estatico
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false


####################
## Swagger
####################
## Configuracoes do Swagger/OpenAPI
springdoc.swagger-ui.path=/swagger.html
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.filter=true


####################
## Profiles
####################
spring.profiles.active=prod
